# Generated by Django 2.1.4 on 2022-11-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='closed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='forum.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thread_creator', to='forum.CustomUser'),
            preserve_default=False,
        ),
    ]
