# Generated by Django 2.1.4 on 2022-11-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20221128_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_post_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
